/* ══════════════════════════════════════════════════════════════
   GRUPOS — Isabella & Samuel · 07.11.2026
   ══════════════════════════════════════════════════════════════ */

const GRUPOS = {
  "cerimonialistas":                    { label: "Cerimonialistas",                     membros: ["Chandde Ramos","Naide Ramos","Davi Ramos","Laura Ramos"] },
  "familia_noivo":                      { label: "Família do Noivo",                    membros: ["André Raimundo Batista","Mirian de Sales Batista","Paulo André Sales Batista"] },
  "familia_noiva":                      { label: "Família da Noiva",                    membros: ["Jarbas Clemente Firmino","Lenita de Paula Clemente","Matheus Clemente de Paula","Lucas de Paula Araújo","Leonor Francisca de Paula"] },
  "padrinho_ester_caiado":              { label: "Padrinho — Ester & Gabriel Caiado",   membros: ["Ester Rodrigues Theco","Gabriel de Luca Caiado"] },
  "padrinho_joel_isabelly_novais":      { label: "Padrinho — Joel & Isabelly Novais",   membros: ["Joel Lucas Muniz Pinheiro","Isabelly Novais Silva","Letícia (irmã da Isabelly Novais)"] },
  "padrinho_jose_rayane":               { label: "Padrinho — José & Rayane",            membros: ["José Henrique Keiji Peres Oyama","Rayane Dias de Almeida da Silva"] },
  "pais_rayane":                        { label: "Pais da Rayane",                      membros: ["Raul Oliveira","Léia Dias"] },
  "padrinho_alexander_danezenha":       { label: "Padrinho — Alexander & Danielly",     membros: ["Alexander Batista de Souza Sacramento","Danielly Alessandra de Souza Veiga"] },
  "padrinho_kauan_isabelly_amiga":      { label: "Padrinho — Kauan & Isabelly",         membros: ["Kauan Parente Araujo","Isabelly Sanches Vargas"] },
  "padrinho_sara_lucas_gomes":          { label: "Padrinho — Sara & Lucas Gomes",       membros: ["Sara Sales Batista","Lucas Gomes Fernandes"] },
  "padrinho_guilherme_larissa":         { label: "Padrinho — Guilherme & Larissa",      membros: ["Guilherme Barboza da Silva","Larissa Kauane Ferreira César"] },
  "padrinho_lucas_arauj_par":           { label: "Padrinho — Lucas Araújo",             membros: ["Lucas de Paula Araújo"] },
  "padrinho_decos_daniela":             { label: "Padrinho — André (Decos) & Daniela",  membros: ["André Vieira Cavalcante Silva","Daniela Vital Alves Sanches"] },
  "familia_vos_noivo":                  { label: "Avós do Noivo",                       membros: ["Maria Deuma de Souza","Heleno Tavares da Silva"] },
  "familia_tio_henrique_geovana":       { label: "Família — Henrique & Geovana",        membros: ["Henrique Tavares da Silva","Geovana Pereira Tavares","Paulo"] },
  "familia_tio_marcos_jessica":         { label: "Família — Marcos & Jéssica",          membros: ["Marcos da Silva","Jéssica Tavares da Silva","Vicente Tavares da Silva","Theo Tavares da Silva"] },
  "familia_tia_maria_lucio":            { label: "Família — Maria & Lúcio",             membros: ["Maria José Sales de Oliveira","Lúcio Dias de Oliveira","Davi Luis Sales de Oliveira"] },
  "familia_casemiro":                   { label: "Família Casemiro",                    membros: ["Cristiane Casemiro","Thiago Casemiro"] },
  "familia_tio_daniel_sonia":           { label: "Família — Daniel & Sônia",            membros: ["Daniel","Sônia"] },
  "familia_noiva_sele_betania_michele": { label: "Família Noiva — Selé & Betânia",      membros: ["Selesiano Soares da Rocha","Betânia Clemente","Micheli Clemente da Rocha","Riquelmy Selesiano da Rocha Alves","Richard da Rocha Alves","Lorena Rafaela da Rocha Bezerra"] },
  "familia_noiva_edna_priscila":        { label: "Família Noiva — Edna & Priscila",     membros: ["Edna Clemente Firmino dos Santos","Priscila C Santos Fernandes","Eduardo Lima Fernandes","Guilherme Andrade dos Santos","Evellyn Clemente dos Santos"] },
  "familia_noiva_cristiane_piracicaba": { label: "Família Noiva — Cristiane (Piracicaba)", membros: ["Cristiane e família"] },
  "familia_noiva_nil":                  { label: "Família Noiva — Nil",                 membros: ["Nil"] },
  "familia_noiva_dalva_ze":             { label: "Família Noiva — Dalva & Zé",          membros: ["Dalva","Zé Rodrigues"] },
  "familia_noiva_katlyn":               { label: "Família Noiva — Katlyn",              membros: ["Katlyn Oliveira","Mario","Calleri","Gael"] },
  "amigos_johnnie_yasmin":              { label: "Amigos — Johnnie & Yasmin",           membros: ["Johnnie Machado Zavatti","Yasmin de Souza Candido"] },
  "amigos_david_elaine":                { label: "Amigos — David & Elaine",             membros: ["David Alves","Elaine Guimarães Bonfim Alves"] },
  "amigos_valeria_lucio_arthur":        { label: "Amigos — Valéria, Lúcio & Arthur",    membros: ["Valéria Gomes Franco","Lúcio Clay da Costa Ferreira Franco","Arthur Clay Gomes Franco"] },
  "amigos_lucas_prado_grupo":           { label: "Amigos — Lucas Prado & Grupo",        membros: ["Lucas Prado","Letícia Nery Barboza","Eduardo Nery","Rayane Andrade"] },
  "amigos_andre_mendonca":              { label: "Amigos — André Mendonça & Família",   membros: ["André Mendonça","Thiago Mendonça","Fernanda Mendonça","Gael Mendonça","Noah Mendonça"] },
  "amigos_rafa_rufino":                 { label: "Amigos — Rafa Rufino",                membros: ["Rafa Rufino"] },
  "amigos_andrei_thais":                { label: "Amigos Z'ele — Andrei & Thaís",       membros: ["Andrei Prado","Thaís Cesario"] },
  "amigos_karine_eraldo_esther":        { label: "Amigos — Karine, Eraldo & Esther",    membros: ["Karine","Eraldo","Esther"] },
  "amigos_saulo_jessica_paiva":         { label: "Amigos — Saulo & Jéssica Paiva",      membros: ["Saulo Paiva","Jéssica Paiva"] },
  "amigos_jeder_suziane":               { label: "Amigos — Jeder, Suziane & Theo",      membros: ["Jeder Camargo","Suziane Nascimento","Theo Nascimento"] },
  "amigos_lucas_medina":                { label: "Amigos — Lucas Medina",               membros: ["Lucas Medina"] },
  "amigos_lais_cunha":                  { label: "Amigos — Laís Cunha",                 membros: ["Lais Cunha"] },
  "amigos_david_thais_franca":          { label: "Amigos — David & Thaís França",       membros: ["David França","Thaís França","Hadassa França"] },
  "nossos_amigos_jefferson_talita":     { label: "Amigos — Jefferson, Talita & Família",membros: ["Jefferson Cancian Lopes","Talita Miranda Lopes","Grazielly Miranda Camarini Lopes","Giullia Miranda Camarini Lopes"] },
  "nossos_amigos_anderson_thais":       { label: "Amigos — Anderson, Thaís & Thomas",   membros: ["Anderson Jardel de Andrade","Thaís Vitória de Andrade","Thomas Vitória de Andrade"] },
  "nossos_amigos_hiro":                 { label: "Amigos — Hiro",                       membros: ["Nicholas Hiroyuki"] },
  "nossos_amigos_davi_aryane":          { label: "Amigos — Davi Monteiro & Aryane",     membros: ["Davi Monteiro","Aryane Monteiro"] },
  "osasco_pedrinho":                    { label: "Osasco — Pedrinho",                   membros: ["Pedro Paulo Ferraz de Oliveira"] },
  "osasco_pedroka":                     { label: "Osasco — Pedroka & Ana Lívia",        membros: ["Pedro Henrique Martins Giovani","Ana Livia Vieira Alves"] },
  "osasco_gabi_laurinha":               { label: "Osasco — Gabi, Laurinha & Maytê",     membros: ["Gabriela Soares Teixeira","Laura Soares Teixeira","Maytê Amaral Daraia Santos"] },
  "laura_kaik":                         { label: "Laura & Kaik",                        membros: ["Laura Carvalho Levi da Silva","Kaik Augusto Ferreira Silva"] },
  "pedro_henrico":                      { label: "Pedro Henrico",                       membros: ["Pedro Henrico"] },
  "caio_amanda":                        { label: "Caio & Amanda",                       membros: ["Caio Vidal Mota","Amanda Boscaro"] },
  "clevi_familia":                      { label: "Clevi Silva & Família",               membros: ["Clevi Silva da Luz","Rebeca Costa e Silva","Lorenzo Costa Carvalho"] }
};

window.GRUPOS = GRUPOS;
